# Generated by Django 4.1 on 2023-03-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField()),
                ("bid", models.IntegerField()),
                ("seatno", models.IntegerField()),
                ("status", models.BooleanField()),
                ("date", models.DateTimeField()),
                ("time", models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bname", models.CharField(max_length=255)),
                ("nos", models.IntegerField()),
                ("fare", models.FloatField()),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                ("bus_operatorid", models.IntegerField()),
                (
                    "dest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dest",
                        to="Bus.location",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="Bus.location",
                    ),
                ),
            ],
        ),
    ]
