# Generated by Django 4.1 on 2023-03-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Bus", "0002_alter_bus_bus_operatorid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="bus_operatorid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
