# Generated by Django 4.1 on 2023-03-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0003_alter_bus_bus_operatorid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bus",
            old_name="bus_operatorid",
            new_name="bus_operator",
        ),
    ]
