# Generated by Django 4.1 on 2023-03-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0005_alter_bus_bus_operator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
