# Generated by Django 4.1 on 2023-03-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0006_alter_booking_date_alter_booking_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="time",
            new_name="booked_date",
        ),
    ]
