# Generated by Django 4.1 on 2023-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0008_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="contact",
            field=models.TextField(null=True),
        ),
    ]
