# Generated by Django 4.1 on 2023-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0012_seat_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
