# Generated by Django 4.1 on 2023-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bus", "0013_booking_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
