# Generated by Django 4.1.7 on 2023-03-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0015_rename_date_booking_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
