# Generated by Django 4.1.7 on 2023-03-18 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0017_alter_booking_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.bus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
