# Generated by Django 4.1.7 on 2023-03-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0019_alter_booking_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bid',
            new_name='bus',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='uid',
            new_name='user',
        ),
    ]
